/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoles } from './UserRoles';
import {
    UserRolesFromJSON,
    UserRolesFromJSONTyped,
    UserRolesToJSON,
    UserRolesToJSONTyped,
} from './UserRoles';

/**
 * 
 * @export
 * @interface AdminChangeRole
 */
export interface AdminChangeRole {
    /**
     * 
     * @type {string}
     * @memberof AdminChangeRole
     */
    email?: string;
    /**
     * 
     * @type {UserRoles}
     * @memberof AdminChangeRole
     */
    newRole?: UserRoles;
}



/**
 * Check if a given object implements the AdminChangeRole interface.
 */
export function instanceOfAdminChangeRole(value: object): value is AdminChangeRole {
    return true;
}

export function AdminChangeRoleFromJSON(json: any): AdminChangeRole {
    return AdminChangeRoleFromJSONTyped(json, false);
}

export function AdminChangeRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminChangeRole {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'newRole': json['newRole'] == null ? undefined : UserRolesFromJSON(json['newRole']),
    };
}

export function AdminChangeRoleToJSON(json: any): AdminChangeRole {
    return AdminChangeRoleToJSONTyped(json, false);
}

export function AdminChangeRoleToJSONTyped(value?: AdminChangeRole | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'newRole': UserRolesToJSON(value['newRole']),
    };
}

