/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserProfile } from './UserProfile';
import {
    UserProfileFromJSON,
    UserProfileFromJSONTyped,
    UserProfileToJSON,
    UserProfileToJSONTyped,
} from './UserProfile';

/**
 * 
 * @export
 * @interface AdminUsers
 */
export interface AdminUsers {
    /**
     * 
     * @type {Array<UserProfile>}
     * @memberof AdminUsers
     */
    users?: Array<UserProfile>;
}

/**
 * Check if a given object implements the AdminUsers interface.
 */
export function instanceOfAdminUsers(value: object): value is AdminUsers {
    return true;
}

export function AdminUsersFromJSON(json: any): AdminUsers {
    return AdminUsersFromJSONTyped(json, false);
}

export function AdminUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): AdminUsers {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserProfileFromJSON)),
    };
}

export function AdminUsersToJSON(json: any): AdminUsers {
    return AdminUsersToJSONTyped(json, false);
}

export function AdminUsersToJSONTyped(value?: AdminUsers | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserProfileToJSON)),
    };
}

