/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppConfig
 */
export interface AppConfig {
    /**
     * 
     * @type {boolean}
     * @memberof AppConfig
     */
    isBackendAware: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppConfig
     */
    user: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppConfig
     */
    adminOnly?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppConfig
     */
    navigation: AppConfigNavigationEnum;
}


/**
 * @export
 */
export const AppConfigNavigationEnum = {
    Bulky: 'bulky',
    Slim: 'slim',
    None: 'none'
} as const;
export type AppConfigNavigationEnum = typeof AppConfigNavigationEnum[keyof typeof AppConfigNavigationEnum];


/**
 * Check if a given object implements the AppConfig interface.
 */
export function instanceOfAppConfig(value: object): value is AppConfig {
    if (!('isBackendAware' in value) || value['isBackendAware'] === undefined) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    if (!('navigation' in value) || value['navigation'] === undefined) return false;
    return true;
}

export function AppConfigFromJSON(json: any): AppConfig {
    return AppConfigFromJSONTyped(json, false);
}

export function AppConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'isBackendAware': json['isBackendAware'],
        'user': json['user'],
        'adminOnly': json['adminOnly'] == null ? undefined : json['adminOnly'],
        'navigation': json['navigation'],
    };
}

export function AppConfigToJSON(json: any): AppConfig {
    return AppConfigToJSONTyped(json, false);
}

export function AppConfigToJSONTyped(value?: AppConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isBackendAware': value['isBackendAware'],
        'user': value['user'],
        'adminOnly': value['adminOnly'],
        'navigation': value['navigation'],
    };
}

