/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangeEmail
 */
export interface ChangeEmail {
    /**
     * 
     * @type {string}
     * @memberof ChangeEmail
     */
    currentEmail: string;
    /**
     * 
     * @type {string}
     * @memberof ChangeEmail
     */
    newEmail: string;
}

/**
 * Check if a given object implements the ChangeEmail interface.
 */
export function instanceOfChangeEmail(value: object): value is ChangeEmail {
    if (!('currentEmail' in value) || value['currentEmail'] === undefined) return false;
    if (!('newEmail' in value) || value['newEmail'] === undefined) return false;
    return true;
}

export function ChangeEmailFromJSON(json: any): ChangeEmail {
    return ChangeEmailFromJSONTyped(json, false);
}

export function ChangeEmailFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangeEmail {
    if (json == null) {
        return json;
    }
    return {
        
        'currentEmail': json['currentEmail'],
        'newEmail': json['newEmail'],
    };
}

export function ChangeEmailToJSON(json: any): ChangeEmail {
    return ChangeEmailToJSONTyped(json, false);
}

export function ChangeEmailToJSONTyped(value?: ChangeEmail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currentEmail': value['currentEmail'],
        'newEmail': value['newEmail'],
    };
}

