/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoggerConfig
 */
export interface LoggerConfig {
    /**
     * 
     * @type {string}
     * @memberof LoggerConfig
     */
    url: string;
}

/**
 * Check if a given object implements the LoggerConfig interface.
 */
export function instanceOfLoggerConfig(value: object): value is LoggerConfig {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function LoggerConfigFromJSON(json: any): LoggerConfig {
    return LoggerConfigFromJSONTyped(json, false);
}

export function LoggerConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoggerConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function LoggerConfigToJSON(json: any): LoggerConfig {
    return LoggerConfigToJSONTyped(json, false);
}

export function LoggerConfigToJSONTyped(value?: LoggerConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

