/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetadataItem
 */
export interface MetadataItem {
    /**
     * 
     * @type {string}
     * @memberof MetadataItem
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof MetadataItem
     */
    value: string;
    /**
     * 
     * @type {boolean}
     * @memberof MetadataItem
     */
    adminOnly?: boolean;
}

/**
 * Check if a given object implements the MetadataItem interface.
 */
export function instanceOfMetadataItem(value: object): value is MetadataItem {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function MetadataItemFromJSON(json: any): MetadataItem {
    return MetadataItemFromJSONTyped(json, false);
}

export function MetadataItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataItem {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
        'adminOnly': json['adminOnly'] == null ? undefined : json['adminOnly'],
    };
}

export function MetadataItemToJSON(json: any): MetadataItem {
    return MetadataItemToJSONTyped(json, false);
}

export function MetadataItemToJSONTyped(value?: MetadataItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
        'adminOnly': value['adminOnly'],
    };
}

