/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';

/**
 * 
 * @export
 * @interface ModelError
 */
export interface ModelError {
    /**
     * 
     * @type {Array<Message>}
     * @memberof ModelError
     */
    warningMessages?: Array<Message>;
    /**
     * 
     * @type {Array<Message>}
     * @memberof ModelError
     */
    errorMessages?: Array<Message>;
}

/**
 * Check if a given object implements the ModelError interface.
 */
export function instanceOfModelError(value: object): value is ModelError {
    return true;
}

export function ModelErrorFromJSON(json: any): ModelError {
    return ModelErrorFromJSONTyped(json, false);
}

export function ModelErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelError {
    if (json == null) {
        return json;
    }
    return {
        
        'warningMessages': json['warningMessages'] == null ? undefined : ((json['warningMessages'] as Array<any>).map(MessageFromJSON)),
        'errorMessages': json['errorMessages'] == null ? undefined : ((json['errorMessages'] as Array<any>).map(MessageFromJSON)),
    };
}

export function ModelErrorToJSON(json: any): ModelError {
    return ModelErrorToJSONTyped(json, false);
}

export function ModelErrorToJSONTyped(value?: ModelError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'warningMessages': value['warningMessages'] == null ? undefined : ((value['warningMessages'] as Array<any>).map(MessageToJSON)),
        'errorMessages': value['errorMessages'] == null ? undefined : ((value['errorMessages'] as Array<any>).map(MessageToJSON)),
    };
}

