/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
    MessageToJSONTyped,
} from './Message';

/**
 * 
 * @export
 * @interface Success
 */
export interface Success {
    /**
     * 
     * @type {Array<Message>}
     * @memberof Success
     */
    messages?: Array<Message>;
    /**
     * 
     * @type {Array<Message>}
     * @memberof Success
     */
    warningMessages?: Array<Message>;
}

/**
 * Check if a given object implements the Success interface.
 */
export function instanceOfSuccess(value: object): value is Success {
    return true;
}

export function SuccessFromJSON(json: any): Success {
    return SuccessFromJSONTyped(json, false);
}

export function SuccessFromJSONTyped(json: any, ignoreDiscriminator: boolean): Success {
    if (json == null) {
        return json;
    }
    return {
        
        'messages': json['messages'] == null ? undefined : ((json['messages'] as Array<any>).map(MessageFromJSON)),
        'warningMessages': json['warningMessages'] == null ? undefined : ((json['warningMessages'] as Array<any>).map(MessageFromJSON)),
    };
}

export function SuccessToJSON(json: any): Success {
    return SuccessToJSONTyped(json, false);
}

export function SuccessToJSONTyped(value?: Success | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'messages': value['messages'] == null ? undefined : ((value['messages'] as Array<any>).map(MessageToJSON)),
        'warningMessages': value['warningMessages'] == null ? undefined : ((value['warningMessages'] as Array<any>).map(MessageToJSON)),
    };
}

