/* tslint:disable */
/* eslint-disable */
/**
 * Swagger - OpenAPI 3.0
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: nikita@ttnr.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const UserRoles = {
    Admin: 'admin',
    User: 'user',
    Unconfirmed: 'unconfirmed'
} as const;
export type UserRoles = typeof UserRoles[keyof typeof UserRoles];


export function instanceOfUserRoles(value: any): boolean {
    for (const key in UserRoles) {
        if (Object.prototype.hasOwnProperty.call(UserRoles, key)) {
            if (UserRoles[key as keyof typeof UserRoles] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserRolesFromJSON(json: any): UserRoles {
    return UserRolesFromJSONTyped(json, false);
}

export function UserRolesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRoles {
    return json as UserRoles;
}

export function UserRolesToJSON(value?: UserRoles | null): any {
    return value as any;
}

export function UserRolesToJSONTyped(value: any, ignoreDiscriminator: boolean): UserRoles {
    return value as UserRoles;
}

