/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 */

package openapi

import (
	validators "template_backend/infrastructure/validators"
)

type UserProfile struct {
	Email string `json:"email" validate:"required,email"`

	Role UserRoles `json:"role" validate:"required,oneof=admin user unconfirmed"`
}

// AssertUserProfileRequired checks if the required fields are not zero-ed
func AssertUserProfileRequired(obj UserProfile) error {
	elements := map[string]interface{}{
		"email": obj.Email,
		"role":  obj.Role,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserProfileConstraints checks if the values respects the defined constraints
func AssertUserProfileConstraints(obj UserProfile) error {
	return validators.Validate.Struct(obj)
}
