// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 */

package openapi




type Config struct {

	App AppConfig `json:"app"`

	Logger LoggerConfig `json:"logger"`
}

// AssertConfigRequired checks if the required fields are not zero-ed
func AssertConfigRequired(obj Config) error {
	elements := map[string]interface{}{
		"app": obj.App,
		"logger": obj.Logger,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	if err := AssertAppConfigRequired(obj.App); err != nil {
		return err
	}
	if err := AssertLoggerConfigRequired(obj.Logger); err != nil {
		return err
	}
	return nil
}

// AssertConfigConstraints checks if the values respects the defined constraints
func AssertConfigConstraints(obj Config) error {
	if err := AssertAppConfigConstraints(obj.App); err != nil {
		return err
	}
	if err := AssertLoggerConfigConstraints(obj.Logger); err != nil {
		return err
	}
	return nil
}
