// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 */

package openapi




type AppConfig struct {

	IsBackendAware bool `json:"isBackendAware"`

	User bool `json:"user"`

	AdminOnly bool `json:"adminOnly,omitempty"`

	Navigation string `json:"navigation"`
}

// AssertAppConfigRequired checks if the required fields are not zero-ed
func AssertAppConfigRequired(obj AppConfig) error {
	elements := map[string]interface{}{
		"isBackendAware": obj.IsBackendAware,
		"user": obj.User,
		"navigation": obj.Navigation,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertAppConfigConstraints checks if the values respects the defined constraints
func AssertAppConfigConstraints(obj AppConfig) error {
	return nil
}
