// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 */

package openapi




type AdminChangeRole struct {

	Email string `json:"email,omitempty"`

	NewRole UserRoles `json:"newRole,omitempty"`
}

// AssertAdminChangeRoleRequired checks if the required fields are not zero-ed
func AssertAdminChangeRoleRequired(obj AdminChangeRole) error {
	return nil
}

// AssertAdminChangeRoleConstraints checks if the values respects the defined constraints
func AssertAdminChangeRoleConstraints(obj AdminChangeRole) error {
	return nil
}
