// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 */

package openapi




type MetadataItem struct {

	Key string `json:"key"`

	Value string `json:"value"`
}

// AssertMetadataItemRequired checks if the required fields are not zero-ed
func AssertMetadataItemRequired(obj MetadataItem) error {
	elements := map[string]interface{}{
		"key": obj.Key,
		"value": obj.Value,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertMetadataItemConstraints checks if the values respects the defined constraints
func AssertMetadataItemConstraints(obj MetadataItem) error {
	return nil
}
