/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	validators "template_backend/infrastructure/validators"
)

type ChangePassword struct {
	CurrentPassword string `json:"currentPassword" validate:"required,pass"`

	NewPassword string `json:"newPassword" validate:"required,pass"`
}

// AssertChangePasswordRequired checks if the required fields are not zero-ed
func AssertChangePasswordRequired(obj ChangePassword) error {
	elements := map[string]interface{}{
		"currentPassword": obj.CurrentPassword,
		"newPassword":     obj.NewPassword,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertChangePasswordConstraints checks if the values respects the defined constraints
func AssertChangePasswordConstraints(obj ChangePassword) error {
	return validators.Validate.Struct(obj)
}
