// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 */

package openapi




type LoggerConfig struct {

	Url string `json:"url"`
}

// AssertLoggerConfigRequired checks if the required fields are not zero-ed
func AssertLoggerConfigRequired(obj LoggerConfig) error {
	elements := map[string]interface{}{
		"url": obj.Url,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertLoggerConfigConstraints checks if the values respects the defined constraints
func AssertLoggerConfigConstraints(obj LoggerConfig) error {
	return nil
}
