/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	validators "template_backend/infrastructure/validators"
)

type UserLogin struct {
	Email string `json:"email" validate:"required,email"`

	Password string `json:"password" validate:"required,pass"`
}

// AssertUserLoginRequired checks if the required fields are not zero-ed
func AssertUserLoginRequired(obj UserLogin) error {
	elements := map[string]interface{}{
		"email":    obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserLoginConstraints checks if the values respects the defined constraints
func AssertUserLoginConstraints(obj UserLogin) error {
	return validators.Validate.Struct(obj)
}
