// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 */

package openapi




type AdminUsers struct {

	Users []UserProfile `json:"users,omitempty"`
}

// AssertAdminUsersRequired checks if the required fields are not zero-ed
func AssertAdminUsersRequired(obj AdminUsers) error {
	for _, el := range obj.Users {
		if err := AssertUserProfileRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertAdminUsersConstraints checks if the values respects the defined constraints
func AssertAdminUsersConstraints(obj AdminUsers) error {
	for _, el := range obj.Users {
		if err := AssertUserProfileConstraints(el); err != nil {
			return err
		}
	}
	return nil
}
