/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"template_backend/database"
	models "template_backend/open-api/models"
)

// StatusAPIRouter defines the required methods for binding the api requests to a responses for the StatusAPI
// The StatusAPIRouter implementation should parse necessary information from the http request,
// pass the data to a StatusAPIServicer to perform the required actions, then write the service results to the http response.
type StatusAPIRouter interface {
	Health(http.ResponseWriter, *http.Request)
}

// StatusAPIServicer defines the api actions for the StatusAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type StatusAPIServicer interface {
	Health(context.Context) (models.ImplResponse, error)
}

// StatusAPIService is a service that implements the logic for the StatusAPIServicer
// This service should implement the business logic for every endpoint for the StatusAPI API.
// Include any external packages or services that will be required by this service.
type StatusAPIService struct {
}

// NewStatusAPIService creates a default api service
func NewStatusAPIService() StatusAPIServicer {
	return &StatusAPIService{}
}

// Health - Check health of server
func (s *StatusAPIService) Health(ctx context.Context) (models.ImplResponse, error) {
	health := models.Health{Server: true, Db: false}
	db, _ := database.Connection.Client.Ping(ctx)
	health.Db = db

	return models.Response(200, health), nil
}
