/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"template_backend/database"
)

// StatusAPIService is a service that implements the logic for the StatusAPIServicer
// This service should implement the business logic for every endpoint for the StatusAPI API.
// Include any external packages or services that will be required by this service.
type StatusAPIService struct {
}

// NewStatusAPIService creates a default api service
func NewStatusAPIService() StatusAPIServicer {
	return &StatusAPIService{}
}

// Health - Check health of server
func (s *StatusAPIService) Health(ctx context.Context) (ImplResponse, error) {
	health := Health{Server: true, Db: false}
	db, _ := database.Connection.Client.Ping(ctx)
	health.Db = db

	return Response(200, health), nil
}
