/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import "template_backend/common"

type UserRegistration struct {
	Email string `json:"email" validate:"required,email"`

	Password string `json:"password" validate:"required,pass"`
}

// AssertUserRegistrationRequired checks if the required fields are not zero-ed
func AssertUserRegistrationRequired(obj UserRegistration) error {
	elements := map[string]interface{}{
		"email":    obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserRegistrationConstraints checks if the values respects the defined constraints
func AssertUserRegistrationConstraints(obj UserRegistration) error {
	return common.Validate.Struct(obj)
}
