/*
 * Swagger - OpenAPI 3.0
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: nikita@ttnr.me
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Success struct {
	Messages []Message `json:"messages"`

	WarningMessages []Message `json:"warningMessages"`
}

// AssertSuccessRequired checks if the required fields are not zero-ed
func AssertSuccessRequired(obj Success) error {
	elements := map[string]interface{}{
		"messages":        obj.Messages,
		"warningMessages": obj.WarningMessages,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Messages {
		if err := AssertMessageRequired(el); err != nil {
			return err
		}
	}
	for _, el := range obj.WarningMessages {
		if err := AssertMessageRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertSuccessConstraints checks if the values respects the defined constraints
func AssertSuccessConstraints(obj Success) error {
	return nil
}
